### ISSUE TITLE
"ArgumentError: Unparseable filesize: 8192 bytes"

### ISSUE THREAD

**Issue by cflannagan** [pawurb/rails-pg-extras#14]
![Screen Shot 2022-01-20 at 12 33 53 AM](https://user-images.githubusercontent.com/214966/150279760-cfdf80ae-df0d-4a28-84d4-bece4883a49b.png)

It's odd - I was seeing output from `RailsPGExtras.diagnose` with no issue, and am now seeing this message, with no change (that I know of) to anything (Gemfile, codebase, the postgresql db, etc). According to output, it couldn't parse "8192 bytes", but when I did that in console, it seems to parse fine with no issue
```
[2] pry(main)> Filesize.parse("8192 bytes")
=> {:prefix=>"", :size=>0.0, :type=>nil}
[3] pry(main)>
```

The other RailsPGExtras outputs work just fine (`db_settings`, `total_index_size`, and so forth on), just not `.diagnose`. 

Gem version is 3.2.5. Rails version 6.1.4.1, Postgresql version 10.13. Ruby version 2.7.4.

I ran `begin; RailsPGExtras.diagnose; rescue => e; puts e.backtrace; end` (saw the other issue, to save you some time). It appears to be coming from this line https://github.com/pawurb/ruby-pg-extras/blob/master/lib/ruby-pg-extras/diagnose_data.rb#L121

Stack trace:
```
[6] pry(main)> begin; RailsPGExtras.diagnose; rescue => e; puts e.backtrace; end
   (12.8ms)  /* Available and installed extensions */

SELECT * FROM pg_available_extensions ORDER BY installed_version;


   (54.1ms)  /* Index and table hit rate */

SELECT
  'index hit rate' AS name,
  (sum(idx_blks_hit)) / nullif(sum(idx_blks_hit + idx_blks_read),0) AS ratio
FROM pg_statio_user_indexes
UNION ALL
SELECT
 'table hit rate' AS name,
  sum(heap_blks_hit) / nullif(sum(heap_blks_hit) + sum(heap_blks_read),0) AS ratio
FROM pg_statio_user_tables;

   (5.4ms)  /* Index and table hit rate */

SELECT
  'index hit rate' AS name,
  (sum(idx_blks_hit)) / nullif(sum(idx_blks_hit + idx_blks_read),0) AS ratio
FROM pg_statio_user_indexes
UNION ALL
SELECT
 'table hit rate' AS name,
  sum(heap_blks_hit) / nullif(sum(heap_blks_hit) + sum(heap_blks_read),0) AS ratio
FROM pg_statio_user_tables;

   (9.5ms)  /* Unused and almost unused indexes */
/* Ordered by their size relative to the number of index scans.
Exclude indexes of very small tables (less than 5 pages),
where the planner will almost invariably select a sequential scan,
but may not in the future as the table grows */

SELECT
  schemaname || '.' || relname AS table,
  indexrelname AS index,
  pg_size_pretty(pg_relation_size(i.indexrelid)) AS index_size,
  idx_scan as index_scans
FROM pg_stat_user_indexes ui
JOIN pg_index i ON ui.indexrelid = i.indexrelid
WHERE NOT indisunique AND idx_scan < 50 AND pg_relation_size(relid) > 5 * 8192
ORDER BY pg_relation_size(i.indexrelid) / nullif(idx_scan, 0) DESC NULLS FIRST,
pg_relation_size(i.indexrelid) DESC;

/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/filesize-0.2.0/lib/filesize.rb:140:in `from'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:121:in `block in unused_indexes'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:120:in `select'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:120:in `unused_indexes'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:48:in `block in call'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:47:in `map'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:47:in `call'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/ruby-pg-extras-3.2.5/lib/ruby-pg-extras/diagnose_data.rb:17:in `call'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rails-pg-extras-3.2.5/lib/rails-pg-extras.rb:54:in `diagnose'
(pry):6:in `<main>'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `eval'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:290:in `evaluate_ruby'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:659:in `handle_line'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `catch'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:260:in `block in eval'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `catch'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:259:in `eval'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:77:in `block in repl'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:67:in `loop'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:67:in `repl'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:38:in `block in start'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/input_lock.rb:61:in `__with_ownership'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/input_lock.rb:78:in `with_ownership'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:38:in `start'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/repl.rb:15:in `start'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/pry_class.rb:191:in `start'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:13:in `start_with_pry_byebug'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:70:in `start'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:19:in `start'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:102:in `perform'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/Users/craig/Documents/projects/octoopi/api/bin/rails:7:in `<main>'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/fork_tracker.rb:10:in `block in fork'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/fork_tracker.rb:8:in `fork'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/fork_tracker.rb:8:in `fork'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/fork_tracker.rb:27:in `fork'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/craig/.rbenv/versions/2.7.4/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
-e:1:in `<main>'
=> nil
```

Thanks in advance!

**Comment by pawurb** [comment]
Thanks for spotting! It was a parsing error, fixed here: https://github.com/pawurb/ruby-pg-extras/commit/1dd8d9587099428046da8caad9acaeceef1c060e 

Fix is now released as 2.3.6
