### ISSUE TITLE
New version errors out - LoadError: cannot load such file -- rails_pg_extras

### ISSUE THREAD

**Issue by kapso** [pawurb/rails-pg-extras#23]
4.1.0 works, but `4.4.1` fails with the following error when deploying our app

```
-----> Detecting rake tasks
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     LoadError: cannot load such file -- rails_pg_extras
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
 !     /tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
 !     /tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
 !     /tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
 !     /tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
 !     /tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
 !     /tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler.rb:176:in `require'
 !     /tmp/build_ee9d9c8a/config/application.rb:7:in `<main>'
 !     /tmp/build_ee9d9c8a/Rakefile:4:in `require_relative'
 !     /tmp/build_ee9d9c8a/Rakefile:4:in `<main>'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
 !     /tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
 !     /tmp/build_ee9d9c8a/bin/rake:4:in `<main>'
 !
/tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/helpers/rake_runner.rb:100:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
rake aborted!
LoadError: cannot load such file -- rails_pg_extras
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
/tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:60:in `block (2 levels) in require'
/tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:55:in `each'
/tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:55:in `block in require'
/tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:44:in `each'
/tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler/runtime.rb:44:in `require'
/tmp/build_ee9d9c8a/vendor/ruby-3.1.1/lib/ruby/3.1.0/bundler.rb:176:in `require'
/tmp/build_ee9d9c8a/config/application.rb:7:in `<main>'
/tmp/build_ee9d9c8a/Rakefile:4:in `require_relative'
/tmp/build_ee9d9c8a/Rakefile:4:in `<main>'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/tmp/build_ee9d9c8a/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/tmp/build_ee9d9c8a/bin/rake:4:in `<main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:967:in `rake'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:69:in `block in run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:63:in `run_assets_precompile_rake_task'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:103:in `block in compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:988:in `allow_git'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/ruby.rb:96:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails2.rb:55:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails3.rb:37:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails4.rb:30:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/rails6.rb:17:in `compile'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:19:in `block in <main>'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/lib/language_pack/base.rb:175:in `log'
	from /tmp/codon/tmp/buildpacks/50d5eddf222a9b7326028041d4e6509f915ccf2c/bin/support/ruby_compile:18:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by pawurb** [comment]
Yeah, removing `require` should fix it. Please reopen if there will still be an issue.
