### ISSUE TITLE
rake pg_extras:outliers fails on Postgres 9.5.21 & Ruby 2.6.6

### ISSUE THREAD

**Issue by brandondrew** [pawurb/rails-pg-extras#3]
```
➲➲💻  rake pg_extras:outliers
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "pg_stat_statements" does not exist
LINE 8: FROM pg_stat_statements WHERE userid = (SELECT usesysid FROM...
             ^
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras.rb:19:in `run_query'
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras.rb:11:in `block (2 levels) in <module:RailsPGExtras>'
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras/tasks/all.rake:9:in `public_send'
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras/tasks/all.rake:9:in `block (3 levels) in <main>'
/Users/brandon/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/Users/brandon/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "pg_stat_statements" does not exist
LINE 8: FROM pg_stat_statements WHERE userid = (SELECT usesysid FROM...
             ^
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras.rb:19:in `run_query'
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras.rb:11:in `block (2 levels) in <module:RailsPGExtras>'
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras/tasks/all.rake:9:in `public_send'
/usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/rails-pg-extras-1.2.1/lib/rails-pg-extras/tasks/all.rake:9:in `block (3 levels) in <main>'
/Users/brandon/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
/Users/brandon/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => pg_extras:outliers
(See full trace by running task with --trace)
```

**Comment by pawurb** [comment]
Hi. You need to enable pg_stat_statements https://www.citusdata.com/blog/2019/02/08/the-most-useful-postgres-extension-pg-stat-statements/
