### ISSUE TITLE
Version 5.4.3 causes an error when initializing the rails application

### ISSUE THREAD

**Issue by jeromepl** [pawurb/rails-pg-extras#48]
The latest version is causing an error in our build pipeline. When trying to call `Rails.application.initialize!` we now get the following error message:

```
#10 6.746 bin/rails aborted!
#10 6.747 No such middleware to insert before: ActionDispatch::Static
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/stack.rb:180:in `assert_index'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.2.2/lib/action_dispatch/middleware/stack.rb:107:in `insert'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/configuration.rb:53:in `block in insert_before'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/configuration.rb:90:in `block in merge_into'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/configuration.rb:89:in `each'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/configuration.rb:89:in `merge_into'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/engine.rb:520:in `block in app'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/engine.rb:517:in `synchronize'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/engine.rb:517:in `app'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `instance_exec'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `run'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:60:in `run_initializers'
#10 6.747 /app/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/application.rb:435:in `initialize!'
#10 6.747 /app/config/environment.rb:7:in `<main>'
```

It looks like it's coming from this change: https://github.com/pawurb/rails-pg-extras/commit/1373fdfd98c1a0f63e892ba99d4f3505414e9b52#diff-2d81478e27e83d2f03ed5223750dac9bd7d6e06c9722e2065f4b0af65839290aR8

**Comment by openbl** [comment]
Also came across this so will close [my issue](https://github.com/pawurb/rails-pg-extras/issues/49)

**Comment by pawurb** [comment]
Please try `5.4.5`

**Comment by jeromepl** [comment]
`5.4.5` resolves the issue, thanks for the quick response!
