### ISSUE TITLE
5.4.2 Breaks API-only Rails Apps

### ISSUE THREAD

**Issue by openbl** [pawurb/rails-pg-extras#49]
## Expected

API-only Rails apps should be able to boot up

## Actual

https://github.com/pawurb/rails-pg-extras/commit/1373fdfd98c1a0f63e892ba99d4f3505414e9b52#diff-2d81478e27e83d2f03ed5223750dac9bd7d6e06c9722e2065f4b0af65839290aR7-R9 seems to fail to boot API-only Rails apps (really Rails apps w/o ActionDispatch::Static in its middleware).

I found this by patching Rails::Configuration::MiddlewareStackProxy

```
irb(#<Rails::Configuration::Middl...):001> args                                                                                                                                                                      
=> [ActionDispatch::Static, ActionDispatch::Static, "/usr/local/bundle/ruby/3.3.0/gems/rails-pg-extras-5.4.3/assets"]                                                                                                
irb(#<Rails::Configuration::Middl...):002>                                                                                                                                                                           
       
/usr/local/bundle/ruby/3.3.0/gems/actionpack-7.1.5/lib/action_dispatch/middleware/stack.rb:179:in `assert_index': No such middleware to insert before: ActionDispatch::Static (RuntimeError)                                    
        from /usr/local/bundle/ruby/3.3.0/gems/actionpack-7.1.5/lib/action_dispatch/middleware/stack.rb:106:in `insert'                                                                                                         
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/configuration.rb:55:in `block in insert_before'                                                                                                         
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/configuration.rb:93:in `block in merge_into'                                                                                                            
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/configuration.rb:92:in `each'                                                                                                                           
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/configuration.rb:92:in `merge_into'                                                                                                                     
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/engine.rb:521:in `block in app'                                                                                                                         
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/engine.rb:518:in `synchronize'                                                                                                                          
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/engine.rb:518:in `app'                                                                                                                                  
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/application/finisher.rb:58:in `block in <module:Finisher>'                                                                                   
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:32:in `instance_exec'                                                                                                       
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:32:in `run'                                                                                                                 
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'                                                                                             
        from /usr/local/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'                                                                                                                                         
        from /usr/local/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'                                                                                                                  
        from /usr/local/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'                                                                                                                      
        from /usr/local/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'                                                                                                                  
        from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each'                                             
        from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `call'                                                                                                                                                          
        from /usr/local/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'                                                                                                                           
        from /usr/local/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'                                                                                                                                                  
        from /usr/local/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'                                                                                                                                                  
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/initializable.rb:60:in `run_initializers'                                                                                                    
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/application.rb:426:in `initialize!'                                                                                                          
        from /app/config/environment.rb:7:in `<main>'                                                                                                                                                                
        from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'                                                                                                                                               
        from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'                                                                                                                   
        from /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                                                                               
        from /usr/local/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'                                                                                                        
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/application.rb:402:in `require_environment!'                                                                                                 
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/command/actions.rb:20:in `boot_application!'                                                                                                 
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/commands/middleware/middleware_command.rb:8:in `perform'                                                                                     
        from /usr/local/bundle/ruby/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'                                                                                                                            
        from /usr/local/bundle/ruby/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'                                                                                                             
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/command/base.rb:178:in `invoke_command'                                                                                                      
        from /usr/local/bundle/ruby/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'                                                                                                                              
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/command/base.rb:73:in `perform'                                                                                                              
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/command.rb:71:in `block in invoke'                                                                                                                      
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/command.rb:149:in `with_argv'                                                                                                                
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/command.rb:69:in `invoke'                                                                                                                               
        from /usr/local/bundle/ruby/3.3.0/gems/railties-7.1.5/lib/rails/commands.rb:18:in `<main>'                                                                                                                   
        from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'                                                                                                                                               
        from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'        
        from /usr/local/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'                                                                                          
        from bin/rails:9:in `<main>' 
```

**Comment by openbl** [comment]
Duplicates https://github.com/pawurb/rails-pg-extras/issues/48
