### ISSUE TITLE
pg_extras:calls and pg_extras:outliers don't work

### ISSUE THREAD

**Issue by Jonskadev** [pawurb/rails-pg-extras#9]
I'm trying to check possible problematic queries that use sequential scans but when I try to get those queries by using calls and/or outliers method there seems to have problems with a missing table.

```
~ bundle exec rake pg_extras:calls
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "total_time" does not exist
LINE 4: interval '1 millisecond' * total_time AS exec_time,
                                   ^
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras.rb:27:in `run_query'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras.rb:12:in `block (2 levels) in <module:RailsPGExtras>'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras/tasks/all.rake:19:in `public_send'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras/tasks/all.rake:19:in `block (3 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'

Caused by:
PG::UndefinedColumn: ERROR:  column "total_time" does not exist
LINE 4: interval '1 millisecond' * total_time AS exec_time,
                                   ^
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/usr/local/bundle/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras.rb:27:in `run_query'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras.rb:12:in `block (2 levels) in <module:RailsPGExtras>'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras/tasks/all.rake:19:in `public_send'
/usr/local/bundle/gems/rails-pg-extras-1.6.0/lib/rails-pg-extras/tasks/all.rake:19:in `block (3 levels) in <main>'
/usr/local/bundle/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.2/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => pg_extras:calls
(See full trace by running task with --trace)
```

The rest of the methods seem to work great and pg_stat_statements seems to be properly installed.

```
+-----------------------------------------------------------------------------------------------------------------------------------+
|                                                Available and installed extensions                                                 |
+--------------------+-----------------+-------------------+------------------------------------------------------------------------+
| name               | default_version | installed_version | comment                                                                |
+--------------------+-----------------+-------------------+------------------------------------------------------------------------+
| plpgsql            | 1.0             | 1.0               | PL/pgSQL procedural language                                           |
| pg_stat_statements | 1.8             | 1.8               | track planning and execution statistics of all SQL statements executed |
| dict_xsyn          | 1.0             |                   | text search dictionary template for extended synonym processing        |
| adminpack          | 2.1             |                   | administrative functions for PostgreSQL                                |
| intarray           | 1.3             |                   | functions, operators, and index support for 1-D arrays of integers     |
...
...
...
...
```

I'm using postgres 13 and rails 6.0.3.4

**Comment by pawurb** [comment]
Hi. Support for `calls` and `outliers` in PG 13 has been added literally yesterday. It should work after upgrading `rails-pg-extras` to `2.0.0`

**Comment by Jonskadev** [comment]
thanks for making this clear, it works now!
